blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.AllPosts.as_view(), name='all_posts'),
    path('<slug:slug>/', views.DetailPost.as_view(), name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
import environ

env = environ.Env()
ENV_PATH = env.str('ENV_PATH')
environ.Env.read_env(ENV_PATH)


urlpatterns = [
    # path('admin/', admin.site.urls),
    path(env('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('sendemail/', views.send_email, name='send_email'),
    path('blog/', include('blog.urls')),
    path('test/', views.test, name='test'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from portfolio.models import Project
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    active = models.BooleanField(default=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=100)
    date = models.DateField(default=timezone.now, editable=True)
    abstract = models.TextField(max_length=500, blank=True)
    image = models.ImageField(upload_to='portfolio/images/', blank=True)
    body = models.TextField()
    likes = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, blank=True)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=64)
    comment = models.TextField()

    def __str__(self):
        return self.name + ': ' + self.comment[:64] + '...'

portfolio/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)
    active_popper = models.BooleanField(default=False)
    summary = models.TextField(max_length=320, default='Working on it...')
    post = models.ForeignKey("blog.Post", on_delete=models.CASCADE, blank=True, null=True)
    url_post = models.URLField(blank=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=320)
    image = models.ImageField(upload_to='portfolio/images/', blank=True)
    url_production = models.URLField(blank=True)
    url_blogpost = models.URLField(blank=True)
    url_github = models.URLField(blank=True)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self) -> str:
        return self.title

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'comment']
        widgets = {'comment': forms.Textarea}

portfolio/forms.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    name = forms.CharField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Post
from .forms import CommentForm
from portfolio.models import Tag

import re


class AllPosts(generic.ListView):
    model = Post
    ordering = ['-id']


class DetailPost(generic.DetailView, generic.edit.FormMixin):
    model = Post
    form_class = CommentForm

    def get_success_url(self):
        return reverse_lazy('blog:detail', kwargs={'slug': self.object.slug})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        comment_form = self.get_form()
        if comment_form.is_valid():
            return self.form_valid(comment_form)
        else:
            return self.form_invalid(comment_form)

    def form_valid(self, form):
        post = self.get_object()
        comment_form = form.save(commit=False)
        comment_form.post = post
        form.save()
        return super(DetailPost, self).form_valid(form)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        tags = {}

        # Add an html popper element for each tag to the dictionary
        for tag in Tag.objects.all():
            if tag.active_popper:
                tags[tag.id] = {
                    # 'length': len(tag.name.split()),
                    'length': len(re.split(' |/', tag.name)),
                    'name': tag.name,
                    'html_element': '<span class="text-popper color-o" tabindex="0" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="{tag_name}" data-bs-content="{tag_summary}" data-url-post="{tag_url_post}">{tag_name}</span>'.format(  # noqa: E501
                        tag_name=tag.name,
                        tag_summary=tag.summary,
                        tag_url_post=tag.url_post)
                }

        # Working context decleration
        post_body = context['post'].body

        # Replace all 2 word long tags with unique id
        # So if they include another tag thats 1 word long they wont get affected by that tag
        for k, v in tags.items():
            if v['length'] > 1:
                padded_id = str(k).zfill(4)
                dollar_k_id = '$$' + padded_id
                s = v['name']

                post_body = re.sub(r'\b%s\b' % s,  dollar_k_id, post_body, flags=re.IGNORECASE)

        for k, v in tags.items():
            if v['length'] <= 1:
                padded_id = str(k).zfill(4)
                dollar_k_id = '$$' + padded_id
                s = v['name']

                post_body = re.sub(r'\b%s\b' % s,  dollar_k_id, post_body, flags=re.IGNORECASE)

        # Replace each instance of the tags from the dictionary in the body of the post with popper element
        for k, v in tags.items():
            padded_id = str(k).zfill(4)
            dollar_k = '$$' + padded_id
            post_body = post_body.replace(dollar_k, v['html_element'])

        # Set context equal to new updated context (working context)
        context['post'].body = post_body
        context['form'] = CommentForm()

        return context

portfolio/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.shortcuts import render
from django.conf import settings
from django.template import loader

import json

# Including for debugging
# from pprint import pprint

from .models import Project
from .forms import ContactForm

from .utils import msg_constructor


def home(request):
    form = ContactForm()
    proj_tags = []

    projects = Project.objects.all()

    for proj in projects:
        for tag in proj.tags.all():
            if tag.name not in proj_tags:
                proj_tags.append(tag.name)

    return render(request, 'portfolio/home.html', {'projects': projects, 'form': form, 'proj_tags': proj_tags})


def send_email(request):
    send_form = ContactForm(request.POST)
    data_valid = False
    if send_form.is_valid():
        data_valid = True
        name = send_form.cleaned_data['name']
        from_email = send_form.cleaned_data['from_email']
        subject = send_form.cleaned_data['subject']
        message = send_form.cleaned_data['message']

        html_message = loader.render_to_string(
            'portfolio/email_template.html', {
                'name': name,
                'from_email':  from_email,
                'subject': subject,
                'message': message
            }
        )

        constructed_message = msg_constructor(name, from_email, subject, message)
        
        try:
            send_mail(
                subject,
                constructed_message,
                settings.EMAIL_HOST_USER,
                [settings.EMAIL_HOST_USER],
                fail_silently=True,
                html_message=html_message,
            )
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return JsonResponse({
            'success_message': 'Your voice is on its way to be heard by me!',
            'data_valid': data_valid
        })
    return JsonResponse({
        'success_message': 'Not able to validate form',
        'form_errors': json.dumps(send_form.errors),
        'data_valid': data_valid
    })


def test(request):
    return render(request, 'portfolio/test.html')

portfolio/templates/portfolio/base.html
{% load static %}
{% load tz %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery so I can run ajax simpler -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'portfolio/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/styles/blog.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/styles/blog-detail.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/styles/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/styles/section.css' %}">

    <link rel="stylesheet" href="{% static 'portfolio/styles/test.css' %}">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;200&family=Roboto:wght@300&display=swap" rel="stylesheet">


    <link rel="icon" type="image/png" href="{% static 'portfolio/assets/recursion.png' %}">

    <title>Kudlanov Portfolio</title>
</head>

<body>

    <!-- Menu not on base template because planning on having a different
    menu on the blog and main site in the future -->
    {% timezone "America/New_York" %}
    {% block content %}{% endblock content %}
    {% endtimezone %}

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <script> 
        // Enabling poppovers sitewide
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'));
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {

            console.log('POPOVER', popoverTriggerEl.dataset.urlPost);
            const urlPost = popoverTriggerEl.dataset.urlPost;

            if (popoverTriggerEl.dataset.urlPost) {
                return new bootstrap.Popover(popoverTriggerEl, {
                    template:  `<div class="popover border border-light rounded" role="tooltip">
                                    <div class="popover-arrow"></div>
                                    <h3 class="popover-header"></h3>
                                    <div class="light-grey-bg rounded-bottom">
                                        <div class="popover-body text-light"></div>
                                        <div class="col text-center">
                                            <a class="btn btn-secondary btn-sm light-grey-bg mb-2" href="${urlPost}" target="_blank" rel="noopener noreferrer">Read More</a>
                                        </div>
                                    </div>
                                </div>`,
                });
            } else {
                return new bootstrap.Popover(popoverTriggerEl, {
                    template:  `<div class="popover border border-light rounded" role="tooltip">
                                    <div class="popover-arrow"></div>
                                    <h3 class="popover-header"></h3>
                                    <div class="light-grey-bg popover-body text-light rounded-bottom"></div>
                                </div>`,
                });
            }
        });
    </script>

</body>

</html>

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<!-- Same menu as on main site because planning on changing the look on the main site -->
<!-- For now just same menu -->
<div class="navbar navbar-dark sticky-top flex-md-nowrap p-0">
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</div>

<div class="container-fluid pt-0">
<div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse pe-2">
        <div class="nav-link">
            <a class="text-decoration-none" href="{% url 'home' %}"><h4 class="my-3">Pavel Kudlanov</h4></a>
            <h5 class="text-muted my-1">Full-Stack</h5>
            <h5 class="text-muted my-1">Software Developer</h5>
        </div>
        <div class="position-sticky pt-3 ps-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:all_posts' %}">
                        <svg class="bi feather" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#vector-pen"/>
                        </svg>
                        Blog
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">
                        <svg class="bi feather" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#house-door"/>
                        </svg>
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}#portfolio-section">
                        <svg class="bi feather" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#layout-text-window-reverse"/>
                        </svg>
                        Projects
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link funny-link" href="{% url 'home' %}#about-section">
                        <svg class="bi feather smile" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#emoji-smile"/>
                        </svg>
                        <svg class="bi feather sunglasses" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#emoji-sunglasses"/>
                        </svg>
                        About
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% static 'portfolio/assets/pavelkudlanov-resume.pdf' %}" target="_blank" rel="noreferrer noopener">
                        <svg class="bi feather" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#file-person"/>
                        </svg>
                        Resume
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}#contact-section">
                        <svg class="bi feather" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#broadcast-pin"/>
                        </svg>
                        Contact
                    </a>
                </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                Social
            </h6>

            <ul class="nav mb-2">
                <li class="nav-item">
                    <a class="nav-link pe-0" href="https://www.linkedin.com/in/pavelkudlanov/" target="_blank" rel="noreferrer noopener">
                        <svg class="bi feather" width="24" height="24" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#linkedin"/>
                        </svg>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pe-0" href="https://github.com/pkudlanov" target="_blank" rel="noreferrer noopener">
                        <svg class="bi feather" width="24" height="24" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#github"/>
                        </svg>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pe-0" href="https://twitter.com/pkudlanov" target="_blank" rel="noreferrer noopener">
                        <svg class="bi feather" width="24" height="24" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#twitter"/>
                        </svg>
                    </a>
                </li>
            </ul>

            <!-- Blog Post Catagories Menu Section For Future-->
            <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                Catagories
            </h6>

            <ul class="nav flex-column mb-2">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">
                        <svg class="bi feather" width="24" height="24" fill="none" stroke="currentColor" stroke-width=".2" stroke-linecap="round" stroke-linejoin="round">
                            <use xlink:href="{% static 'portfolio/assets/bootstrap-icons.svg' %}#vector-pen"/>
                        </svg>
                        Catogory Ex.
                    </a>
                </li>
            </ul> -->
        </div>
    </nav>

    <main id="blog" class="col-md-9 ms-sm-auto col-lg-10 my-0 py-0">
        {% block blog_content %}{% endblock blog_content %}
    </main>
</div>
</div>
{% endblock content %}

portfolio/templates/portfolio/test.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block content %}

<div class="navbar navbar-dark sticky-top flex-md-nowrap p-0">
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</div>


<div class="row m-0">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse pe-2">
        <div class="position-sticky pt-3 ps-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="...">Some Place</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="...">Some Other Place</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="...">Where Am I?</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="...">What Do You Need?!!!!</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="...">HELP STUPID PROGRAM</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="...">I WILL END YOU STUPID PAGE!!!</a>
                </li>
            </ul>
        </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 p-0 testt">
        <div id="home-section" class="section position-relative">
            <div class="banner mb-4">
                <div class="overlay position-relative">
                </div>
            </div>

            <div class="text-part justify-content-center">
                <h1>Hello Top</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste tempora atque totam? Voluptatibus similique sed magni amet perferendis dicta maiores assumenda reiciendis nam iste facilis totam atque, soluta molestias omnis?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste tempora atque totam? Voluptatibus similique sed magni amet perferendis dicta maiores assumenda reiciendis nam iste facilis totam atque, soluta molestias omnis?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste tempora atque totam? Voluptatibus similique sed magni amet perferendis dicta maiores assumenda reiciendis nam iste facilis totam atque, soluta molestias omnis?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste tempora atque totam? Voluptatibus similique sed magni amet perferendis dicta maiores assumenda reiciendis nam iste facilis totam atque, soluta molestias omnis?</p>
            </div>
        </div>
    </main>
</div>

{% endblock content %}